# Generated by Django 5.0.3 on 2024-03-20 12:10

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overview', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='account',
        ),
        migrations.AddField(
            model_name='stock',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stock',
            name='maximum_value',
            field=models.FloatField(verbose_name='Valor de Venda'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='minimum_value',
            field=models.FloatField(verbose_name='Valor de Compra'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='ticker',
            field=models.CharField(max_length=10, verbose_name='Ticker da Ação'),
        ),
        migrations.CreateModel(
            name='StockHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.FloatField(verbose_name='Preço da Ação')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Data de Registro')),
                ('stock_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='overview.stock')),
            ],
        ),
        migrations.DeleteModel(
            name='Account',
        ),
    ]
